version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: liquor_sales_IA_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: cs620ibdc1234
      POSTGRES_DB: IowaLiquorSales
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data 
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql:ro

  dataloader:
    build: .
    container_name: dataloader
    depends_on:
      - db
    volumes:
      - ./:/app
    command: python DataLoader.py

volumes:
  db_data:

