services:
  db:
    image: mysql/mysql-server:latest
    container_name: liquor_sales_IA_db
    environment:
      MYSQL_ROOT_PASSWORD: cs620ibdc1234
      MYSQL_DATABASE: IowaLiquorSales
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

